<?php

namespace Espo\Modules\AdvancedCrosstab\Tools\Export;

use Espo\Core\Exceptions\BadRequest;
use Espo\Core\Job\JobSchedulerFactory;
use Espo\Core\Utils\Config;
use Espo\Core\Utils\Language;
use Espo\Entities\Attachment;
use Espo\Modules\AdvancedCrosstab\Engine\Definition\Definition;
use Espo\Modules\AdvancedCrosstab\Engine\Limits;
use Espo\Modules\AdvancedCrosstab\Engine\Pivot\PivotEngine;
use Espo\Modules\AdvancedCrosstab\Engine\Query\UserContext;
use Espo\Modules\AdvancedCrosstab\Jobs\ExportJob;
use Espo\ORM\EntityManager;
use Espo\Core\ORM\Repository\Option\SaveOption;

/**
 * Server-side export. Small results are generated immediately; large ones are generated by a background job
 * which notifies the user with a download link.
 */
class ExportService
{
    public function __construct(
        private PivotEngine $pivotEngine,
        private EntityManager $entityManager,
        private JobSchedulerFactory $jobSchedulerFactory,
        private Exporter $exporter,
        private UserContext $userContext,
        private Config $config,
        private Language $language,
        private Limits $limits,
    ) {}

    /**
     * @return array{attachmentId?: string, async?: bool}
     */
    public function export(Definition $definition, string $format, string $title, bool $forceSync = false): array
    {
        if (!isset(Exporter::FORMATS[$format])) {
            throw new BadRequest("Unsupported export format.");
        }

        $result = $this->pivotEngine->run($definition);

        $cellCount = 0;

        foreach ($result['cells'] as $columns) {
            $cellCount += count($columns) * max(1, count($result['valueColumns']));
        }

        if (!$forceSync && $cellCount > $this->limits->asyncExportCellThreshold()) {
            $this->jobSchedulerFactory
                ->create()
                ->setClassName(ExportJob::class)
                ->setData([
                    'userId' => $this->userContext->getUser()->getId(),
                    'definition' => $definition->raw,
                    'format' => $format,
                    'title' => $title,
                ])
                ->schedule();

            return ['async' => true];
        }

        return ['attachmentId' => $this->generate($result, $format, $title)];
    }

    public function generate(array $result, string $format, string $title): string
    {
        $grid = Grid::fromResult($result, $this->language->translateLabel('Total', 'labels', 'AdvancedCrosstab'));

        $contents = $this->exporter->render(
            $grid,
            $format,
            $title,
            $this->createFormatter(),
            (string) ($this->config->get('exportDelimiter') ?: ',')
        );

        $fileName = preg_replace('/[^\p{L}\p{N}\-_ ]+/u', '', $title) ?: 'crosstab';
        $fileName = trim($fileName) . ' ' . date('Y-m-d') . '.' . Exporter::FORMATS[$format]['extension'];

        /** @var Attachment $attachment */
        $attachment = $this->entityManager->getRDBRepositoryByClass(Attachment::class)->getNew();

        $attachment
            ->setName($fileName)
            ->setRole(Attachment::ROLE_EXPORT_FILE)
            ->setType(Exporter::FORMATS[$format]['mimeType'])
            ->setContents($contents);

        $this->entityManager->saveEntity($attachment, [
            SaveOption::CREATED_BY_ID => $this->userContext->getUser()->getId(),
        ]);

        return $attachment->getId();
    }

    private function createFormatter(): ValueFormatter
    {
        $thousandSeparator = $this->config->get('thousandSeparator');
        $decimalMark = $this->config->get('decimalMark');

        return new ValueFormatter(
            $thousandSeparator === null ? ',' : (string) $thousandSeparator,
            $decimalMark ? (string) $decimalMark : '.',
            $this->config->get('defaultCurrency')
        );
    }
}
